#db:
#  host: 'localhost'
#  username: 'postgres'
#  password: 'd3L0R3AN_31'
#  synchronize: true

db:
  host: 'ec2-52-1-95-247.compute-1.amazonaws.com'
  username: 'iwmxxbqwivsvok'
  password: '26c87da7ad2b632864ef69b3246c50f5d5e9f565a2e0d4a344d321a042bfee3b'
  synchonize: false

jwt:
  secret: 'topSecret51'